# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed474a9690680ff56af6dbd9de6e7ecc2c16b0f63b549c185ca737b74e08dd1d5e9bd283748b596c5bdbe72133083e5f831dbf97d29d800ae87dab7cb7159547

test:
  secret_key_base: f34b8a49cb22182cdcdcd0f5ea0348d7a72975f7cf8d1e9f83942fb867297626009e09cbdc7db717f122e6580e584069ed66ba9430a80d069309fe66c52ae15f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
